/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { AiOutlineArrowRight } from "react-icons/ai";
import { Profile } from "@/components/Button";
import { Account } from "@/components/Account";
import {
  MediaRenderer,
  useActiveClaimConditionForWallet,
  useAddress,
  useClaimConditions,
  useClaimerProofs,
  useClaimIneligibilityReasons,
  useContract,
  useContractMetadata,
  useTotalCirculatingSupply,
  Web3Button,
} from "@thirdweb-dev/react";
import { useAccount } from "wagmi";
import { useMemo, useState } from "react";
import { Skeleton, SkeletonCircle, SkeletonText } from "@chakra-ui/react";

const myEditionDropContractAddress =
  "0xa0B1De7eaC31f9ea2625e2fc7917af8F7905bA27";

export default function Home() {
  const { contract: editionDrop } = useContract(myEditionDropContractAddress);
  const { data: contractMetadata } = useContractMetadata(editionDrop);
  const tokenId = 0;
  const [quantity, setQuantity] = useState(0);
  //get address of conected wallet
  const { address, connector, isConnected } = useAccount();
  console.log(contractMetadata, address, "data");
  return (
    <>
      <Head>
        <title>minto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-[20px]  h-full w-full">
        <header className="w-full">
          <h5
            className="font-[700] tracking-[1.5px] text-4xl text-red-600 mb-5 italic"
            style={{
              fontFamily: "'Libre Baskerville', serif",
            }}
          >
            Minto
          </h5>
        </header>
        <section className=" md:grid-cols-2 grid grid-cols-1 lg:grid-cols-2   h-[700px] w-[100vw] ">
          <div>
            <div className="flex flex-col gap-2">
              <h2
                className="text-5xl tracking-[1.5px]"
                style={{
                  fontFamily: "'Libre Baskerville', serif",
                }}
              >
                <span className="font-[700] tracking-[1.5px]">Mint</span>And
                <span className="font-[700] tracking-[1.5px]">Sell</span>{" "}
              </h2>

              <div className="flex items-center">
                <h2
                  className="text-5xl font-[700] tracking-[1.5px]"
                  style={{
                    fontFamily: "'Libre Baskerville', serif",
                  }}
                >
                  Web3
                </h2>
                <Image
                  width={64}
                  height={64}
                  src="https://img.icons8.com/wired/64/null/stormtrooper.png"
                  alt={""}
                />
              </div>
              <h2
                className="text-4xl tracking-[1.5px] bg-red-600 text-white w-[200px] p-2"
                style={{
                  fontFamily: "'Libre Baskerville', serif",
                }}
              >
                DigitalArt
              </h2>
              <p
                className="mt-10 text-xl md:text-2xl"
                style={{
                  fontFamily: "'Raleway', sans-serif",
                }}
              >
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod
                quasi porro iure esse rerum. Nam incidunt nihil aliquam libero
                veritatis?
              </p>

              <Profile />
              <div className="bg-white w-[40%] h-full flex items-center justify-center "></div>
            </div>
          </div>
          <div>
            <div className="h-full w-[100%] md:w-[80%] lg:w-[70%] mx-auto mt-[20px] md:mt-0 ">
              {contractMetadata ? (
                <div className=" flex flex-col  w-[90%] h-full  p-[10px] align-center gap-2 border-[2px] border-black">
                  <p
                    className="font-[600] text-center mt-10 tracking-[1.5px] text-xl uppercase"
                    style={{
                      fontFamily: "'Raleway', sans-serif",
                    }}
                  >
                    {contractMetadata?.name}
                  </p>
                  {/* Image Preview of NFTs */}
                  <MediaRenderer
                    className="w-full h-[300px] mx-auto rounded-[10px] border-black border-[2px]"
                    src={contractMetadata?.image}
                    alt={`${contractMetadata?.name} preview image`}
                  />
                  <p
                    className="font-[200] text-center mt-10 tracking-[1.5px] text-xl"
                    style={{
                      fontFamily: "'Raleway', sans-serif",
                    }}
                  >
                    {contractMetadata?.description}
                  </p>
                  <p
                    className="font-[400] text-center my-5 tracking-[1.5px] text-xl"
                    style={{
                      fontFamily: "'Raleway', sans-serif",
                    }}
                  >
                    Quantity
                  </p>
                  <div className="flex items-center justify-center gap-[20px]">
                    <button
                      onClick={() => setQuantity((_) => _ + 1)}
                      className="text-[20px] font-bold bg-slate-300 rounded-full h-[50px] w-[50px]"
                    >
                      +
                    </button>
                    <span>{quantity}</span>
                    <button
                      onClick={() => setQuantity((_) => _ - 1)}
                      className="text-[20px] font-bold bg-slate-300 rounded-full h-[50px] w-[50px]"
                    >
                      -
                    </button>
                  </div>

                  <p
                    className="font-[600] text-center mt-10 tracking-[1.5px] text-xl uppercase"
                    style={{
                      fontFamily: "'Raleway', sans-serif",
                    }}
                  >
                    Minting...
                  </p>
                </div>
              ) : (
                <div className=" flex flex-col  w-[90%] h-full  p-[10px] align-center gap-2 border-[2px] border-gray-300">
                  <SkeletonText
                    mt="4"
                    noOfLines={1}
                    spacing="4"
                    skeletonHeight="50px"
                  />
                  <Skeleton
                    height="300px"
                    width="300px"
                    mx="auto"
                    rounded="10px"
                  />
                  <Skeleton height="50px" mt="5" />
                  <Skeleton height="50px" mt="5" />
                  <div className="flex items-center justify-center gap-[20px]">
                    <Skeleton
                      className="text-[20px] font-bold bg-slate-300 rounded-full h-[50px] w-[50px]"
                      rounded="100%"
                    />
                    <SkeletonText
                      mt="4"
                      noOfLines={1}
                      spacing="4"
                      skeletonHeight="50px"
                    />
                    <Skeleton
                      className="text-[20px] font-bold bg-slate-300 rounded-full h-[50px] w-[50px]"
                      rounded="100%"
                    />
                  </div>
                </div>
              )}
            </div>
          </div>
        </section>
        <section>
          <Account />
        </section>
      </main>
    </>
  );
}
