/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { AiOutlineArrowRight } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>minto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-[20px]">
        <header className="w-full">
            <h5 className="font-[700] tracking-[1.5px] text-4xl text-red-600 mb-5 italic"  style={{
                  fontFamily: "'Libre Baskerville', serif",
                }}>Minto</h5>
        </header>
        <section className=" md:grid-cols-2 grid grid-cols-1 lg:grid-cols-2   h-[700px] w-[100vw] ">
          <div>
            <div className="flex flex-col gap-2">
              <h2
                className="text-5xl tracking-[1.5px]"
                style={{
                  fontFamily: "'Libre Baskerville', serif",
                }}
              >
                <span className="font-[700] tracking-[1.5px]">Mint</span>And
                <span className="font-[700] tracking-[1.5px]">Sell</span>{" "}
              </h2>

              <div className="flex items-center">
                <h2
                  className="text-5xl font-[700] tracking-[1.5px]"
                  style={{
                    fontFamily: "'Libre Baskerville', serif",
                  }}
                >
                  Web3
                </h2>
                <Image width={64} height={64} src="https://img.icons8.com/wired/64/null/stormtrooper.png" alt={""} />
              </div>
              <h2
                className="text-5xl tracking-[1.5px]"
                style={{
                  fontFamily: "'Libre Baskerville', serif",
                }}
              >
                DigitalArt
              </h2>
              <p
                className="mt-10 text-xl md:text-2xl"
                style={{
                  fontFamily: "'Raleway', sans-serif",
                }}
              >
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod
                quasi porro iure esse rerum. Nam incidunt nihil aliquam libero
                veritatis?
              </p>
              <div className="bg-black flex w-[200px] gap-3 h-[60px] mt-10 items-center  border-black border-[2px]">
                <button  className=" text-xl text-[100] text-white w-full "
                style={{
                  fontFamily: "'Raleway', sans-serif",
                }}>Connect Wallet</button>
              <div className="bg-white w-[40%] h-full flex items-center justify-center "> <AiOutlineArrowRight className="text-red-600 font-[400] text-[24px]"/></div>
              </div>
            </div>
          </div>
          <div>
            <div className="h-full w-[100%] md:w-[80%] lg:w-[70%] mx-auto mt-[20px] md:mt-0 " >
              <div className=" flex flex-col  w-[90%] h-full  p-[10px] align-center gap-2 border-[2px] border-black">
               <Image width={300} height={300} className="w-[300px] h-[300] mx-auto rounded-[100%] border-black border-[2px]" src="/img1.jpg" alt={""} />
                <p className="font-[600] text-center mt-10 tracking-[1.5px] text-xl uppercase" style={{
                  fontFamily: "'Raleway', sans-serif",
                }}>Minting...</p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
